# Generated by Django 4.1.7 on 2023-02-22 15:32

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('CL', 'Клиент'), ('WK', 'Исполнитель'), ('ADM', 'Администратор'), ('MNG', 'Менеджер')], max_length=50, null=True, verbose_name='Роль пользователя')),
                ('tg_id', models.IntegerField(verbose_name='Telegram ID юзера')),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU', verbose_name='Контактный номер')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('WAIT', 'Ожидает принятия'), ('WORK', 'В работе'), ('DONE', 'Завершена')], default='WAIT', max_length=50, verbose_name='статус')),
                ('task', models.TextField(verbose_name='Задача')),
                ('created_at', models.DateTimeField(verbose_name='Публикация задачи')),
                ('end_at', models.DateTimeField(verbose_name='Конец задачи')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_tasks', to='telegram_bot.user', verbose_name='Клиент')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_tasks', to='telegram_bot.user', verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lvl', models.CharField(choices=[('NA', 'Не активна'), ('ECO', 'Экономный'), ('DEFAULT', 'Стандарт'), ('VIP', 'ВИП')], default='NA', max_length=50, verbose_name='Уровень подписки')),
                ('starts_at', models.DateTimeField(verbose_name='Начало подписки')),
                ('end_at', models.DateTimeField(verbose_name='Конец подписки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='telegram_bot.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
    ]
