# Generated by Django 4.1.7 on 2023-02-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=' ', max_length=50, verbose_name='Имя пользователя'),
            preserve_default=False,
        ),
    ]
