# Generated by Django 4.1.7 on 2023-02-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0002_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CL', 'Клиент'), ('WK', 'Исполнитель'), ('ADM', 'Администратор'), ('MNG', 'Менеджер')], default='CL', max_length=50, verbose_name='Роль пользователя'),
        ),
    ]
