# Generated by Django 4.1.7 on 2023-02-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0004_alter_task_end_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Конец задачи'),
        ),
    ]
