# Generated by Django 4.1.7 on 2023-02-25 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0007_support'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at'], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterModelOptions(
            name='support',
            options={'ordering': ['created_at'], 'verbose_name': 'Поддержка', 'verbose_name_plural': 'Поддержки'},
        ),
    ]
